% Limit Order Book with Zero-Intelligence Constrained Traders
% Simulates a market with five buyers and five sellers.
% Buyers submit random bids no higher than their individual valuations.
% Sellers submit random asks no lower than their individual costs.
% Matching orders execute at the resting order's price.
% Each trader can complete one transaction and then becomes inactive.
% The simulation records trader IDs, transaction prices and trade surplus.
% Market efficiency is calculated as realised surplus divided by
% the maximum achievable surplus, expressed as a percentage.
% A fixed random seed makes the simulation reproducible.


clear; close all; clc
rng(1)

v = [110 108 106 104 102]; %creating the vector for the buying values
c = [96 98 100 105 107]; %the vector for sellers costs
Pmin = 90; % we set the lower bound
Pmax = 120; % and the upper bound
T = 1000; %the ammount os simulations we will do 

activeB = true(1, 5); %we set al the buyers active as to can take place into the simulation
activeS = true(1, 5); %we set the sellers active as tehy can take part into the simulation
bid = -inf(1, 5); % we set that the buyer has no active offer
ask = inf(1, 5); % and the same for the sellere

trade = []; %we create the arrays again for trade
buyer = []; %we create the arrays again for buyers
seller = []; %we create the arrays again for sellers
surplus = []; %we create the arrays again for ssurplus 

V = sort(v, 'descend'); % we set thevalues from larger to smales 
C = sort(c, 'ascend'); %and we set the values from lower to largest
Smax = sum(max(V - C, 0)); % we find the maximum surplus the market can generate if it is 100% efficient
                           % because we need to supdtruct the maximum value
                           % from the minimum and go on
for t = 1:T
    if ~any(activeB) || ~any(activeS) %if no buyers and sellers remain then break
        break
    end

    b = 0;
    s = 0;
    buy = rand < 0.5;

    if buy
        ids = find(activeB);
        i = ids(randi(length(ids))); % select a buyer randomly generating probability from unifmr distribution
        price = randi([Pmin v(i)]); % and then generate a price from the boundaries we have set
        [p, j] = min(ask);

        if price >= p % if the price generated is higher than the price in the minimum asked we proceed
            b = i;
            s = j;
        else
            bid(i) = price; 
        end
    else
        ids = find(activeS); %find the active buyers
        i = ids(randi(length(ids))); 
        price = randi([c(i) Pmax]); %the price is generated randomly between the max price and the vectors
        [p, j] = max(bid); %and we find the maximum bid

        if price <= p
            b = j;
            s = i;
        else
            ask(i) = price;
        end
    end

    if b > 0
        trade(end+1) = p; % the trader price goes into the next available position
        buyer(end+1) = b; % the buyer price goes into the next available position
        seller(end+1) = s; % the seller price goes into the next available position
        surplus(end+1) = v(b) - c(s); %the surplus that was generated by the market is going to the last available position
        activeB(b) = false; % we make the buyer inactive as to not participate in future trades
        activeS(s) = false;  % we make the seller inactive as to not participate in future trades
        bid(b) = -inf;
        ask(s) = inf;
    end
end

Sreal = sum(surplus); %the real surplus is calculated as the sum of the surpluses we have added to the array
E = 100 * Sreal / Smax; %and then we calculate the efficiency
results = table(buyer', seller', trade', surplus', ...
    'VariableNames', {'Buyer', 'Seller', 'Price', 'Surplus'});
disp(results)
disp(['Maximum surplus = ' num2str(Smax)])
disp(['Realised surplus = ' num2str(Sreal)])
disp(['Efficiency (%) = ' num2str(E)])

plot(trade, '-o')
xlabel('Trade number')
ylabel('Transaction price')
title('Zero-intelligence constrained traders')
